# vim: ft=tmux
set -g mode-style "fg=#a0a8b7,bg=#282c34"

set -g message-style "fg=#a0a8b7,bg=#282c34"
set -g message-command-style "fg=#a0a8b7,bg=#282c34"

set -g pane-border-style "fg=#282c34"
set -g pane-active-border-style "fg=#a0a8b7"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#535965,bg=#1f2329"
set -g status-bg "#1f2329"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

# Left: session > user > window index
set -g status-left "#[fg=#1f2329,bg=#e2b86b,bold] #S #[fg=#e2b86b,bg=#7a818e]#[fg=#1f2329,bg=#7a818e,bold] #(whoami) #[fg=#7a818e,bg=#535965]#[fg=#a0a8b7,bg=#535965] #I #[fg=#535965,bg=#1f2329] "

# Right: hostname
set -g status-right "#[fg=#535965,bg=#1f2329]#[fg=#a0a8b7,bg=#535965] #h "

setw -g window-status-activity-style "underscore,fg=#7a818e,bg=#1f2329"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#7a818e,bg=#1f2329"

# Inactive window
setw -g window-status-format "  #[fg=#7a818e]#I #W  "

# Active window with arrows
setw -g window-status-current-format "#[fg=#1f2329,bg=#e2b86b]#[fg=#1f2329,bg=#e2b86b,bold] #I #W #[fg=#e2b86b,bg=#1f2329]"
