#### COLOUR (onedark.nvim "darker" — matches nvim, ghostty & vi-mongo)

# default statusbar colors
set-option -g status-style bg=#1f2329,fg=#7a818e,default

# default window title colors
set-window-option -g window-status-style fg=#7a818e,bg=#1f2329,dim

# active window title colors
set-window-option -g window-status-current-style fg=#e2b86b,bg=default,bright

# pane border
set-option -g pane-border-style fg=#282c34
set-option -g pane-active-border-style fg=#a0a8b7,bg=#282c34

# message text
set-option -g message-style bg=#282c34,fg=#a0a8b7

# pane number display
set-option -g display-panes-active-colour "#4fa6ed"
set-option -g display-panes-colour "#e2b86b"

# clock
set-window-option -g clock-mode-colour "#48b0bd"
